// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQk1hbzrDTV_s1eSeTyqzrS5BSf4prsrk',
    appId: '1:246661865141:web:f862129550caa23cac68fc',
    messagingSenderId: '246661865141',
    projectId: 'siirart',
    authDomain: 'siirart.firebaseapp.com',
    storageBucket: 'siirart.firebasestorage.app',
    measurementId: 'G-7DJ6MV0XRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANAReUoWnQO5wCHdFfRsk-LGs2TWX_pr0',
    appId: '1:246661865141:android:7ad35401969f097fac68fc',
    messagingSenderId: '246661865141',
    projectId: 'siirart',
    storageBucket: 'siirart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGTPbSPgP-zGZjqtm3H4rN_fCPVCUjRxE',
    appId: '1:246661865141:ios:8157dc6ab92a7bc5ac68fc',
    messagingSenderId: '246661865141',
    projectId: 'siirart',
    storageBucket: 'siirart.firebasestorage.app',
    iosBundleId: 'com.siirart.poem.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGTPbSPgP-zGZjqtm3H4rN_fCPVCUjRxE',
    appId: '1:246661865141:ios:a64343820d81f846ac68fc',
    messagingSenderId: '246661865141',
    projectId: 'siirart',
    storageBucket: 'siirart.firebasestorage.app',
    iosBundleId: 'com.example.poemapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQk1hbzrDTV_s1eSeTyqzrS5BSf4prsrk',
    appId: '1:246661865141:web:6febd0a399911258ac68fc',
    messagingSenderId: '246661865141',
    projectId: 'siirart',
    authDomain: 'siirart.firebaseapp.com',
    storageBucket: 'siirart.firebasestorage.app',
    measurementId: 'G-MJFYB28K20',
  );

}